### ISSUE TITLE
didMetadataStructureTest_r is not defined

### ISSUE THREAD

**Issue by fqutishat** [w3c/did-test-suite#112]
```
    ReferenceError: didMetadataStructureTest_r is not defined

      24 |             Object.keys(didDocumentMetadata).forEach((property_name) => {
      25 |                 if (typeof didDocumentMetadata[property_name] == "object") {
    > 26 |                     didMetadataStructureTest_r(didDocumentMetadata[property_name]);
         |                     ^
      27 |                 }
      28 |             });
      29 |         });

      at forEach (suites/did-core-properties/did-metadata-structure.js:26:21)
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (suites/did-core-properties/did-metadata-structure.js:24:46)
```

https://github.com/w3c/did-test-suite/blob/333b1220483d31d723004a036e1c74e0243d1aac/packages/did-core-test-server/suites/did-core-properties/did-metadata-structure.js#L26

**Comment by fqutishat** [comment]
I think there is typo in method name should be didMetadataStructureTests

**Comment by shigeya** [comment]
@fqutishat Thank you very much for spotting this. This code path is not used unless you run with a property with an object as a value.

 If you need to run the test, please rename

`didMetadataStructureTest_r`

to 

`didMetadataStructureTest_Map_Recursive`

Then, it should work.

I will create PR for the repository.

**Comment by shigeya** [comment]
@fqutishat The current head of the main branch merged the fix. please try. 

@msporny Please mark this issue as pending close.

**Comment by msporny** [comment]
> @msporny Please mark this issue as pending close.

We only need to do that on DID Core... we can close issues on the test suite as they're confirmed. All we need is @fqutishat to say you fixed his issue and we can close.

**Comment by fqutishat** [comment]
@msporny @shigeya I have this error now 
```
 ● 7.3 Metadata Structure - did:orb - DID Orb Test Suite - SecureKey › did:orb:interim:EiC-dLIbtnkHnfc6_Wkc8-X8Ag8FhvpC-jIMrT29_S_ttw › application/did+ld+json › 7.3 Metadata Structure - The values within any complex data structures such as maps and lists MUST be one of these data types as well.

    Tests cannot be nested. Test "7.3 Metadata Structure - The structure used to communicate this metadata MUST be a map of properties." cannot run because it is nested within "7.3 Metadata Structure - The values within any complex data structures such as maps and lists MUST be one of these data types as well.".

      1 | const didMetadataStructureTest_Map_Recursive = (didDocumentMetadata) => {
    > 2 |     it('7.3 Metadata Structure - ' +
        |     ^
      3 |        'The structure used to communicate this metadata MUST be a map of properties.', () => {
      4 |         expect(didDocumentMetadata).toBeInfraMap();
      5 |     });

      at Env.it (node_modules/jest-jasmine2/build/jasmine/Env.js:605:19)
      at didMetadataStructureTest_Map_Recursive (suites/did-core-properties/did-metadata-structure.js:2:5)
      at forEach (suites/did-core-properties/did-metadata-structure.js:26:21)
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (suites/did-core-properties/did-metadata-structure.js:24:46)
```

**Comment by shigeya** [comment]
@fqutishat Ah, right. I see. I need to find a workaround...

Would you please provide the implementation JSON data you have? via gist.github.com or other ways? then I can fix the problem.

**Comment by troyronda** [comment]
@shigeya Please see PR #117

**Comment by shigeya** [comment]
@troyronda @fqutishat thanks. Will fix it tomorrow Japanese time.

**Comment by shigeya** [comment]
@troyronda @fqutishat PR #122 addressed the above issue.

**Comment by fqutishat** [comment]
@shigeya thank you for your fix but now I have new error
```
   TypeError: expect(...).toBeDidDocumentMap is not a function

      30 |                             Object.keys(didDocumentMetadata).forEach((property_name) => {
      31 |                                 if (typeof didDocumentMetadata[property_name] == "object") {
    > 32 |                                     expect(didDocumentMetadata[property_name]).toBeDidDocumentMap();
         |                                                                                ^
      33 |                                 }
      34 |                             });
      35 |                         });

```

**Comment by shigeya** [comment]
@fqutishat That's odd. Did you ran `lerna run prepare` at the top level?

**Comment by fqutishat** [comment]
@shigeya yes it works now after run ```lerna run prepare``` at the top level. I will close the issue.
