### ISSUE TITLE
Test server's generate-test won't run

### ISSUE THREAD

**Issue by csuwildcat** [w3c/did-test-suite#119]
I have double checked I installed everything (installed lerna globally, and executed `npm i` at the root), but still fails with the following error:

```
$ npm run generate-report

> did-core-test-server@1.0.0 generate-report C:\repos\did-test-suite\packages\did-core-test-server
> node generate-latest-respec-data.js

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './suites/did-spec/default.json'
Require stack:
- C:\repos\did-test-suite\packages\did-core-test-server\generate-latest-respec-data.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\repos\did-test-suite\packages\did-core-test-server\generate-latest-respec-data.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\repos\\did-test-suite\\packages\\did-core-test-server\\generate-latest-respec-data.js'
  ]
}
```

**Comment by OR13** [comment]
I think you may need to pull latest, I think this issue has been fixed in subsequent PRs

**Comment by csuwildcat** [comment]
@OR13 I believe I just did a full reset to start from the very latest code from the main repo as of this morning, but I will double check to make sure.

**Comment by csuwildcat** [comment]
@OR13 you were right, I was a bit stale - sorry for the spurious report!
